### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by woozycherri** [Milxnor/Project-Reboot-3.0#1]
Leave a comment

**Comment by rallll** [comment]
![image](https://github.com/Milxnor/Project-Reboot-3.0/assets/83738650/efdda736-25fd-45f1-8f78-1d849e2fd55f)

**Comment by rallll** [comment]
![image](https://github.com/Milxnor/Project-Reboot-3.0/assets/83738650/e931abf8-646e-42bf-be41-ebf70aae2896)

**Comment by Ender-0001** [comment]
autistic retards

**Comment by Milxnor** [comment]
that is not nice ender
![image](https://github.com/Milxnor/Project-Reboot-3.0/assets/84999745/e751cc0c-7210-4a70-a635-270546908cef)

**Comment by OGFN** [comment]
spastics

**Comment by woozycherri** [comment]
![image](https://github.com/Milxnor/Project-Reboot-3.0/assets/68205825/37cea139-9ab0-4f4c-85bf-6723636ce9a0)
thats so crazy
