### ISSUE TITLE
MarkArrayDirty Finder?

### ISSUE THREAD

**Issue by FlashCoder2024** [Milxnor/Project-Reboot-3.0#109]
would be a perfect idea to add MarkArrayDirty to every season
Season 3.5: "48 89 5C 24 ? 57 48 83 EC 20 80 B9 ? ? ? ? ? 48 8B FA 48 8B D9 75 4A C6 81 ? ? ? ? ? 48 81 C1 ? ? ? ? 83 3A FF 75 16 FF 41 50 8B 41 50 89 02 33 D2 8B 41 50 83 F8 FF 0F 44 C2 89 41 50"

**Comment by Milxnor** [comment]
What my brother?
