### ISSUE TITLE
Samsung Intensity 3 Support?

### ISSUE THREAD

**Issue by GDBOI101** [Milxnor/Project-Reboot-3.0#11]
Why no inject dll on Samsung Intensity 3 Verizon Wireless phone .apk no install and fortnite old phone website scam me.
How fix?

I need skin in game 7.40 multiplayer!

**Comment by bren2409** [comment]
u haz to fix it in hxd bro just do that

**Comment by GDBOI101** [comment]
Hxd installer no open cannot patch game file!

**Comment by bren2409** [comment]
get the Samsung Intensity 4 Verizon Wireless phone

**Comment by GDBOI101** [comment]
To expensive no affordable
