### ISSUE TITLE
Rebot No working 25.11!!!

### ISSUE THREAD

**Issue by GDBOI101** [Milxnor/Project-Reboot-3.0#27]
I open fortnite epik gams lancher injekt dll crash and ban me pls help fix need host latist game for my dad no have pc!!!

**Comment by max8447** [comment]
how tf

**Comment by MagmaDev12** [comment]
omg juts open the epik gams and fornyiet and remov antichit and tel mr epik gams to add rebot suport to latest!1!!!!!1!

**Comment by Twin1dev** [comment]
what hte hej!!!
