### ISSUE TITLE
NO AMAZON SUPPORT [VIDEO]

### ISSUE THREAD

**Issue by JoshAltosino** [Milxnor/Project-Reboot-3.0#29]
IM SO MAD BECAUSE MY AMAZON ECHO DOESNT WORK AND IT PIES ME OFF LOOK! #

https://github.com/Milxnor/Project-Reboot-3.0/assets/80610960/af2fb22c-2f3f-4d18-a884-faca6f635c73

**Comment by GDBOI101** [comment]
Is this fix four rebot gamserver latist?

**Comment by JoshUnscripted** [comment]
> Is this fix four rebot gamserver latist?

NO!!!!! I TRIES MICROWAVING AND IT DIDNT WORK

**Comment by MagmaDev12** [comment]
BRO PUT IT IN YO DISHWASHER IT MADE MY ALEXA HAVE PROJIECT REBOT!!111!

**Comment by JoshUnscripted** [comment]
THATS IT IM GOING TO MAKE GOURMET FOOD WITH MY AMAZON REBOOT THEN IT WILL WORK

https://github.com/Milxnor/Project-Reboot-3.0/assets/80610960/bb23bcf8-db4d-4909-a6d5-b6ac8a98c9b0

**Comment by GDBOI101** [comment]
Why no worked?

**Comment by Jagger24x24** [comment]
works on newest update

**Comment by TimmieDevelops** [comment]
no work - no gameserver

**Comment by GDBOI101** [comment]
Fixed yet yes?
