### ISSUE TITLE
Building from code

### ISSUE THREAD

**Issue by xLoigi** [Milxnor/Project-Reboot-3.0#30]
![image](https://github.com/Milxnor/Project-Reboot-3.0/assets/79259439/6f999b75-cee5-490b-b984-54710caf55fc)
It just gives me this errors. I did nothing to it.

**Comment by Noggo123** [comment]
Nice

**Comment by GDBOI101** [comment]
Roblox

**Comment by xLoigi** [comment]
ok im gonna try that

**Comment by techsideofficial** [comment]
FIX THIS NOW

**Comment by Fehype** [comment]
This can help:
https://learn.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=msvc-170
Just follow the steps and you can build, remember to change build to release.

**Comment by Noggo123** [comment]
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎

**Comment by NiwiSB** [comment]
Change to Release
