### ISSUE TITLE
Can I use this on windows server?

### ISSUE THREAD

**Issue by rudle2207** [Milxnor/Project-Reboot-3.0#38]
Is there a way to make this run on windows server?
If not, are there any alternatives seeing as this is discontinued, and raider only works with 3.5

**Comment by Cane2612-bit** [comment]
Download the reboot launcher on the mc store
you can do everything easily from there

**Comment by rudle2207** [comment]
https://github.com/Auties00/reboot_launcher
This?

**Comment by rudle2207** [comment]
if you mean microsoft store it isnt on there
the main reason why im asking so much is because i'm trying to find a good way of hosting/joininh a fortnite server just to mess around with thats open source, I did find era launcher and that worked fine but i was a bit urked because it had a dll that was in c++ while the rest of it was decompilable in c# so that urked me a bit

**Comment by rudle2207** [comment]
sorry i'm going on for so long its just everything seems like its disappeared or fallen into obscurity and isn't trustworthy in these fortnite servers

**Comment by AlexDev404** [comment]
@rudle2207 Yeah I know the guy who made it. It's safe, but he's just weird when it comes to releasing his source code. I don't know where you can find the DLLs, but you can surely ask him on Discord at <@839920351416025108>

**Comment by Milxnor** [comment]
> @rudle2207 Yeah I know the guy who made it. It's safe, but he's just weird when it comes to releasing his source code. I don't know where you can find the DLLs, but you can surely ask him over on Discord at <@839920351416025108>

even though I have open sourced the most things in the community? Your delusional.

**Comment by Jagger24x24** [comment]
everything is oss except the fortniteconsole dll if your not stupid you could find it

**Comment by Milxnor** [comment]
> everything is oss except the fortniteconsole dll if your not stupid you could find it

(fyi its literally an older Fortnite-Structs commit BARELY modified)

**Comment by AlexDev404** [comment]
> everything is oss except the fortniteconsole dll if your not stupid you could find it

That statement makes no sense. Do you now see why Fortnite modding has never really taken off? It's because of the lack of support and people like you all who expect people to "not be stupid" and dig around hundreds of commits searching for God-knows what just to compile one piece of code.

**Comment by Milxnor** [comment]
> AlexDev404

there is no closed source version here you go again assuming all of this stuff. "Are we all already supposed to know that?" either look into it or don't say anything like you have...

**Comment by AlexDev404** [comment]
> > > everything is oss except the fortniteconsole dll if your not stupid you could find it
> > 
> > 
> > That statement makes no sense. Do you now see why Fortnite modding has never really taken off? It's because of the lack of support and people like you all who expect people to "not be stupid" and dig around hundreds of commits searching for God-knows what just to compile one piece of code.
> 
> legit open your fucking eyes in the reboot launcher it tells you exactly what each dll does and if you used your fucking brain you could just search it up

Child, open your eyes and get that zoomer ass off of that chair and get a job. Nobody even asked for your informational screenshot of the descriptions of what each of the components do. This entire conversation started when I just tried to help out one guy.

> legit open your fucking eyes in the reboot launcher...

Do you see the Reboot **launcher** being linked in this repository? I believe not. So that is my point.

> if you used your fucking brain you could just search it up

Oh really now? And how many grown-ups you think have a Discord account? Not much!


And papi, this conversation is already over :)
Already had my conversation with Gray personally.

I find **no interest** in shouting crossway and getting nowhere in forums (especially with children) when I can just talk to someone like adults.

Have a nice day:)

**Comment by Jagger24x24** [comment]
> https://github.com/Auties00/reboot_launcher This?

here

> > > > everything is oss except the fortniteconsole dll if your not stupid you could find it
> > > 
> > > 
> > > That statement makes no sense. Do you now see why Fortnite modding has never really taken off? It's because of the lack of support and people like you all who expect people to "not be stupid" and dig around hundreds of commits searching for God-knows what just to compile one piece of code.
> > 
> > 
> > legit open your fucking eyes in the reboot launcher it tells you exactly what each dll does and if you used your fucking brain you could just search it up
> 
> Child, open your eyes and get that zoomer ass off of that chair and get a job. Nobody even asked for your informational screenshot of the descriptions of what each of the components do. This entire conversation started when I just tried to help out one guy.
> 
> > legit open your fucking eyes in the reboot launcher...
> 
> Do you see the Reboot **launcher** being linked in this repository? I believe not. So that is my point.
> 
> > if you used your fucking brain you could just search it up
> 
> Oh really now? And how many grown-ups you think have a Discord account? Not much!
> 
> And papi, this conversation is already over :) Already had my conversation with Gray personally.
> 
> I find **no interest** in shouting crossway and getting nowhere in forums (especially with children) when I can just talk to someone like adults.
> 
> Have a nice day:)

You are actually blind the second comment talks about the reboot launcher of another repository, It is very childish to simply call another childish. Also I told you to search something up on Github or Google not Discord being an adult has nothing to do with that. You say "searching for God-knows what" I responded to that saying exactly what you need to search up and how it would not be hard to find the information to search up.

You legit started your conversation mocking somebody for not releasing the source code to something, that isn't helpful that is just  harassment of a third party.

> @rudle2207 Yeah I know the guy who made it. It's safe, but he's just weird when it comes to releasing his source code. I don't know where you can find the DLLs, but you can surely ask him over on Discord at <@839920351416025108>

This was your first message and I don't see in any way how this could help anyone with the issue of "Can I use this on windows server?".

**Comment by wryern** [comment]
what the hell is watch.exe, in the reboot launcher? 
[https://github.com/Auties00/reboot_launcher/blob/master/gui/assets/misc/watch.exe](url)
it has no background info on it and is completely closed source, we know what the dlls do, doesn't mean they're safe
fact the launcher doesn't compile and barely has any info on it outside of the github is sketch as all hell to me

If anyone can tell me what the fuck is watch.exe is that would be helpful, thanks

**Comment by Jagger24x24** [comment]
https://github.com/Auties00/reboot_launcher/blob/master/watch/lib/watch.dart
Here is the source for that exe. It is not supposed to be there its supposed to be compiled when you compile the reboot launcher but this was probably just a mistake in the gitignore thus the file was put in the project files.

**Comment by Milxnor** [comment]
I am pretty sure watch.exe is to watch for when your main Fortnite client closes so it can close the suspended anticheats & launcher.
