### ISSUE TITLE
Bot Lobby Playlist

### ISSUE THREAD

**Issue by Sir-DJ-Cat** [Milxnor/Project-Reboot-3.0#50]
Hey, didn't know how else to reach you so figured I'd pop this in here. I'm trying to use reboot to load up a bot match using this playlist I got from the playlist dump:
`/Game/Athena/Playlists/DefaultBots/Playlist_Bots_DefaultSolo.Playlist_Bots_DefaultSolo`
However I can't seem to figure out how to properly load it. Any ideas? :)

**Comment by UnNyanCat** [comment]
bro really thought reboot support bots match

**Comment by Sir-DJ-Cat** [comment]
What wouldn’t it? The scripts are there, the playlist is there, seems like there should be some way to access it

**Comment by UnNyanCat** [comment]
it's just not supported.

**Comment by Jurij15** [comment]
The playlist is, but just having a playlist won't spawn bots. That would have to be implemented on the server.

**Comment by Milxnor** [comment]
Bots/Working AI are not planned for V3
