### ISSUE TITLE
Skins from locker don’t work on 4.1-4.5

### ISSUE THREAD

**Issue by godbot100** [Milxnor/Project-Reboot-3.0#59]

**Comment by UWUFN** [comment]
can vouch, mcp does not work on versions 4.1 through 4.5.

**Comment by Therealsxlar** [comment]
MCP on 4.1 through 4.5 work for me

**Comment by Therealsxlar** [comment]
Nah I didn't use any skin pak. I just used a dedicated server milxnor provided and it worked.

**Comment by Milxnor** [comment]
Being resolved soon
