### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by frustlyy** [Milxnor/Project-Reboot-3.0#61]
when I try to host server I click start hosting for a few seconds it gives me stop hosting then it gives me start hosting and in the meantime it gives me continuously without stopping launching the headless server (the version is 4.5) what should I do
![Immagine 2024-02-09 161447](https://github.com/Milxnor/Project-Reboot-3.0/assets/147253829/ee0a312d-d697-48d0-b4c4-62e35f92407b)

**Comment by Jagger24x24** [comment]
This is not the repo for the launcher however it can be found here https://github.com/Auties00/reboot_launcher
