### ISSUE TITLE
Please Rename Repo

### ISSUE THREAD

**Issue by GDBOI101** [Milxnor/Project-Reboot-3.0#70]
Istfg if I have to search "reboot 3.0" again I'll die. Please just rename it to RebootV3 (Milxnor please continue to skip sckule and make best fourtniyte prodgect please 1:1 dedi UE6 Support plz bro!)

**Comment by Jagger24x24** [comment]
This can be solved by not skidding

**Comment by GDBOI101** [comment]
No! My brother Damien Savanamonkol sent me this for ImpulseFN! I didn't mean to click the link but now im addicted.

**Comment by Milxnor** [comment]
yap
