### ISSUE TITLE
19.10 crashing on start

### ISSUE THREAD

**Issue by Kreozx** [Milxnor/Project-Reboot-3.0#76]
when i open chapter 3 it just crashes saying something about direct x12 and direct x 11

**Comment by ApfelTeeSaft** [comment]
Then you need a Better GPU, this has nothing to do with Reboot

**Comment by MrHackerTool** [comment]
When i open 16.40 or any other seasons it crashes and says, "Cannot Log into Fortnite: authcation error

**Comment by Jagger24x24** [comment]
These are both not game server related issues one is a graphics driver related issue which has to do with the game itself and the other is a backend error.

**Comment by Kvisla1210** [comment]
20.40 just crashes when i go into the lobby

**Comment by max8447** [comment]
not a gs issue

**Comment by Ducki67** [comment]
> 20.40 just crashes when i go into the lobby

Skill issue then

**Comment by Ducki67** [comment]
i figured out that you will have to use Starfall.dll  for Auth patch  OR Carniumv2.dll

**Comment by mevenv10-hub** [comment]
<img width="713" height="361" alt="Image" src="https://github.com/user-attachments/assets/10a16aa2-458a-40ce-bf74-631f38681853" />

why does it do this before launching

**Comment by ApfelTeeSaft** [comment]
> <img width="713" height="361" alt="Image" src="https://github.com/user-attachments/assets/10a16aa2-458a-40ce-bf74-631f38681853" />
> 
> why does it do this before launching

Are you perhaps on ARM windows?

**Comment by Ducki67** [comment]
> > <img alt="Image" width="713" height="361" src="https://private-user-images.githubusercontent.com/253474728/532769709-10a16aa2-458a-40ce-bf74-631f38681853.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njc3OTAxMTYsIm5iZiI6MTc2Nzc4OTgxNiwicGF0aCI6Ii8yNTM0NzQ3MjgvNTMyNzY5NzA5LTEwYTE2YWEyLTQ1OGEtNDBjZS1iZjc0LTYzMWYzODY4MTg1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEwN1QxMjQzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTU0ZjBkY2I3MDI2MGEwZTc2MzZhYjQ5MDIzMzQ2MTUyNzQyZjY4ZWFiNzRiZDRkOGJmYmNhYTg0MjExNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UQrIcaoxXnhPsXN-irIA-AVXjZ9p3dVM9KxdobqO44Y">
> > why does it do this before launching
> 
> Are you perhaps on ARM windows?

Prob ARM ngl  cuz I have a friend who has the same shit today still
