### ISSUE TITLE
const constructor - builds, but crashes on inject

### ISSUE THREAD

**Issue by NotJeppy** [Milxnor/Project-Reboot-3.0#87]
I already told Milxnor about this but the change in BitArray.h DOES allow it to build, but it crashes upon injection. I have zero clue how to fix that lol

**Comment by max8447** [comment]
that makes no sense

**Comment by NotJeppy** [comment]
> that makes no sense

tf you mean that makes no sense? VS updated and now throws an error on a const constructor (shouldn't have been able to compile at ALL, but nonetheless it worked until this update)|

now, with the "fix", it compiles, makes a dll, yet closes the game after injection. idk what you want from me

**Comment by max8447** [comment]
how would an iterator not having a const constructor crash it

**Comment by NotJeppy** [comment]
> how would an iterator not having a const constructor crash it

buddy I'm not a genie I honestly couldn't tell ya.

two days ago I compile and host just fine on Jeppy Hosting.

yesterday I update VS for another project and suddenly I get the new error

today I realize he put a fix out for it and now it will compile, yet crashes.

no other code changes were made during this time. I literally just checked my history. So... 

I mean honestly I kinda stopped asking questions about why stuff does what it does in this project. Chapter 2 stuff is like mega skunked imo

**Comment by Milxnor** [comment]
it is not because of the const constructor crashing it i believe they changed how the projectr compiles with the new update Hope this helps :)

**Comment by max8447** [comment]
well thats not good

**Comment by MarvelcoOGFN** [comment]
just use compiler versoin 143

**Comment by NotJeppy** [comment]
> just use compiler versoin 143

you know, it's sad that I didn't know you could do that. I thought you were locked to the latest compiler version after updating.

**Comment by NotJeppy** [comment]
> just use compiler versoin 143

uhh bad news boys. I am using v143.

**Comment by MarvelcoOGFN** [comment]
> > just use compiler versoin 143
> 
> uhh bad news boys. I am using v143.

well works fine to me even before milxnor fixed compiling

**Comment by NotJeppy** [comment]
> well works fine to me even before milxnor fixed compiling

Did you update to 17.11.2?

**Comment by MarvelcoOGFN** [comment]
> > well works fine to me even before milxnor fixed compiling
> 
> Did you update to 17.11.2?

No I never updated vs cause ik shit like this happens

**Comment by NotJeppy** [comment]
good point. 

Solution was to delete vs and then reinstall it. idk why this fixes it.

I'll drop containers spawning loot after being broken in a pr in a few minutes.
