### ISSUE TITLE
Did the discord server get deleted?

### ISSUE THREAD

**Issue by kostasIsHere123** [Milxnor/Project-Reboot-3.0#93]
It just dissapeared infront of my eyes and I do not seem to be able to access it from any of my accounts, I also don't think im banned.

**Comment by Milxnor** [comment]
GG.

**Comment by kostasIsHere123** [comment]
what happened???

**Comment by Milxnor** [comment]
look at readme

**Comment by kostasIsHere123** [comment]
welp, GG's that was so sudden... Thanks you for such an amazing project!

**Comment by 1m4b0t** [comment]
![image](https://github.com/user-attachments/assets/753535ec-3233-4f7d-968c-0daf893a0c9c)
i've been away from the og/modding community for a while and yesterday i suddenly saw this, i thought it was weird that i got kicked/banned so i looked if there was something besides the discord and got here, it's really sad to see this go away

**Comment by ProjectNeptuneMP** [comment]
Milxnor Please dont do this to us we want project reboot and we want v4 we really like the game server and reboot has a big community. please milxnor get reboot back!!!

**Comment by kostasIsHere123** [comment]
> ###
> [Oct 15, 2024](#issuecomment-2414666384)

I don't want reboot to get cancelled either but this might be hard on the dev. (but I am sure that if he remade the discord then he would get half of the community back)

**Comment by AlexDev404** [comment]
IMO you don't need a Discord server to have a community. Have a good project, and people will come to you without prompt.

**Comment by Milxnor** [comment]
reboot never had advertising it grew via sharing and I am aware we dont need discord
