### ISSUE TITLE
Please continue the project

### ISSUE THREAD

**Issue by AlexDev404** [Milxnor/Project-Reboot-3.0#96]
I know we have had our differences, and have never once seen eye to eye--but that doesn't mean that I do not respect you for your work. You are good at what you do--and everyone and you know it.

You may feel like you have reached the end of the road for now, but that doesn't mean that all is lost. You have a great project, and one that I feel as if has a lot of potential to become even more than what it is right now. Your community still exists and will always still exist as long as this repository and you do.

Please continue with your work. The practicality of stopping now after all that you've done and worked for these past several years is not a wise decision.

I could say much more, but I believe I've said enough with this to carry across my point.

I am looking forward to seeing you work on your fourth revision on the project. If you need anything, please feel free to reach out. You have my contact information. I may be busy, but I will do what I can to assist you getting back on your feet--or whatever you may need. And either way, I'm sure the rest of your community would not have an issue with this either.

I wish you all the best, Gray.

**Comment by ProjectNeptuneMP** [comment]
PLEASE CONTINUE MILXNOR!!

**Comment by LeproideOFF** [comment]
Plezzzzzz just create à New account or telegram

**Comment by Milxnor** [comment]
i am only quitting reboot, the discord will come back if I get my account back except a lot will probably change and be properly moderated

**Comment by AlexDev404** [comment]
> i am only quitting reboot, the discord will come back if I get my account back except a lot will probably change and be properly moderated

Okay, well take care man. Sorry about what happened to you.
Looking forward to hopefully seeing your community coming back :)

**Comment by Milxnor** [comment]
comm is 6 more feet under on December 6th
