### ISSUE TITLE
Fake discord

### ISSUE THREAD

**Issue by LeproideOFF** [Milxnor/Project-Reboot-3.0#97]
![Screenshot_20241018-075724_Discord](https://github.com/user-attachments/assets/67647525-0b6e-427b-9eb6-bd1b414103ed)

**Comment by Milxnor** [comment]
What do you want me to do about it?

**Comment by LeproideOFF** [comment]
Its you or another person because its the same discord server

**Comment by Milxnor** [comment]
not me
